require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/companies", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Company. As you add validations to Company, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryBot.build(:company).attributes.symbolize_keys
  }

  let(:invalid_attributes) {
    { marketcap: nil }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # CompaniesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  before(:each) do
    @company = create(:company)
  end

  after(:each) do
    if @company
      @company.destroy!
    end
  end

  describe "GET /index" do
    it "renders a successful response" do
      get companies_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      get company_url(@company), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Company" do
        expect {
          post companies_url,
               params: { company: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Company, :count).by(1)

        @company = Company.find_by_ticker(@company.ticker)
      end

      it "renders a JSON response with the new company" do
        post companies_url,
             params: { company: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
        @company = Company.find_by_ticker(@company.ticker)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Company" do
        expect {
          post companies_url,
               params: { company: invalid_attributes }, as: :json
        }.to change(Company, :count).by(0)
      end

      it "renders a JSON response with errors for the new company" do
        post companies_url,
             params: { company: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
        @company = Company.find_by_ticker(@company.ticker)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { marketcap: Faker::Number.number(digits: 5)}
      }

      it "updates the requested company" do
        old_mc = @company.marketcap
        patch company_url(@company),
              params: { company: new_attributes }, headers: valid_headers, as: :json
        @company.reload
        expect(@company).to be_valid
        expect(@company.marketcap).to_not eq(old_mc)
        @company = Company.find_by_ticker(@company.ticker)
      end

      it "renders a JSON response with the company" do
        patch company_url(@company),
              params: { company: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
        @company = Company.find_by_ticker(@company.ticker)
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the company" do
        patch company_url(@company),
              params: { company: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
        @company = Company.find_by_ticker(@company.ticker)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested company" do
      expect {
        delete company_url(@company), headers: valid_headers, as: :json
      }.to change(Company, :count).by(-1)
    end
  end
end
